name: Deploy Laravel


on:
    push:
        branches:
            - main

jobs:
    create-deployment-artifacts:
        name: Create Deployment Artifacts

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2


            - name: build docker image
              run: docker build -f nginxdockerfile -t  laravel-app:1.0.0 .

            - name: push docker image
              run: |
               docker save hh-docker:0.0.2 -o hh-docker.tar
               chmod 644 hh-docker.tar 



