name: Deploy Laravel


on:
    push:
        branches:
            - main

jobs:
    create-deployment-artifacts:
        name: Create Deployment Artifacts

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: compile css and js  
              run : npm install && npm run prod
