name: Deploy Laravel


on:
    push:
        branches:
            - main

jobs:
    create-deployment-artifacts:
        name: Create Deployment Artifacts

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2


            - name: build docker image
              run: docker build -f nginxdockerfile -t  laravel-app:1.0.0 .

            - name: push docker image
              run: |
               docker save laravel-app:1.0.0 -o laravel-app.tar
               chmod 644 laravel-app.tar

            

            - name: Copy nginx docker image to droplet
              uses: appleboy/scp-action@v0.1.7
              with:
                 host: ${{secrets.HOST}}
                 username: ${{secrets.USERNAME}}
                 key: ${{secrets.KEY}}
                 source: laravel-app.tar
                 target: ~/images



